# idp.yml
development:
  idp_metadata: ""
  idp_metadata_ttl: ""
  assertion_consumer_service_url: ""
  assertion_consumer_service_binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
  name_identifier_format: "urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified"
  issuer: ""
  authn_context: ""
  idp_sso_target_url: ""
  idp_cert: 