# idp.yml
development:
  idp_metadata: ""
  idp_metadata_ttl: ""
  assertion_consumer_service_url: ""
  assertion_consumer_service_binding: ""
  name_identifier_format: ""
  issuer: ""
  authn_context: ""
  idp_sso_target_url: ""
  idp_cert: 