default:
  jetty_port: 8983
  java_opts:
    - "-XX:MaxPermSize=128m"
    - "-Xmx256m"

test:
  jetty_port: <%= ENV['TEST_JETTY_PORT'] || 8888 %> 
  jetty_home: <%= ENV['TEST_JETTY_PATH'] || File.join(Rails.root, 'test_jetty') %>
  startup_wait: 15
  java_opts:
    - "-XX:MaxPermSize=128m"
    - "-Xmx256m"